services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    InspiredMinds\ContaoExtendedFormFieldsBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Form,Resources}
